name: Hattac Precast
favicon: null
layout_spectrum: 0.3875201737973839
typography_spectrum: 0.10730203031562269
title: Hattac Precast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3475cd'
    - '#0000cc'
    - '#afc2da'
    - '#0f0f0f'
  brandStrength: 0.7221000243443996
  lightness: 0.34241257165558636
  saturation: 0.8009552345611155
  rhythmicContrast: 0.20640654116868973
purpose: []
